<?php
/**
 * IGC_G_Record class extends IGC_Record. The G Record verifies that the
 * ASCII data has not been altered during or following the flight.
 *
 * @see IGC_Record
 *
 * @version 0.1
 * @author Mike Milano <coder1@gmail.com>
 * @project php-igc
 */
class IGC_G_Record extends IGC_Record
{
  /**
   * The security code is a <= 75 byte string generated by the FDR. The manufacturer provides
   * methods to check the integrity of the file within the security code.
   *
   * @access public
   * @var string
   */
  public $security_code;

  /**
   * Class constructor creates the G record from the raw IGC string
   *
   * @param     string  $record
   */
  public function __construct($record)
  {
    $this->type = 'G';
    $this->raw = $record;

    $this->security_code = substr($record,1);
  }
}
?>
