#
# Makefile
# Michael Zapf, 2016-02-04 19:43
#

all: mac-test

clean:
	rm -rf mac-test

mac-test:
	gcc -pedantic -Werror -std=c99 -o mac-test mac-test.c ../../firmware/src/mac/mac.c

# vim:ft=make
#
